export const userConstants = {

	LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
	LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',

	SIGNUP_PHOTO: 'USERS_SIGNUP_PHOTO',
	SIGNUP_REQUEST: 'USERS_SIGNUP_REQUEST',
	SIGNUP_SUCCESS: 'USERS_SIGNUP_SUCCESS',

	// RESENDEMAIL_REQUEST: 'USERS_RESENDEMAIL_REQUEST',
	// RESENDEMAIL_SUCCESS: 'USERS_RESENDEMAIL_SUCCESS',
	// RESETPASSEMAIL_REQUEST: 'USERS_RESETPASSEMAIL_REQUEST',
	// RESETPASSEMAIL_SUCCESS: 'USERS_RESETPASSEMAIL_SUCCESS',
	// RESETPASS_REQUEST: 'USERS_RESETPASS_REQUEST',
	// RESETPASS_SUCCESS: 'USERS_RESETPASS_SUCCESS',

	LOGOUT: 'USERS_LOGOUT',

	// GETUSER_REQUEST: 'USERS_GETUSER_REQUEST',
	// GETUSER_SUCCESS: 'USERS_GETUSER_SUCCESS',

	// GETPROFILE_REQUEST: 'USERS_GETPROFILE_REQUEST',
	// GETPROFILE_SUCCESS: 'USERS_GETPROFILE_SUCCESS',
	
	// DELETE_REQUEST: 'USERS_DELETE_REQUEST',
	// DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
	// DELETE_FAILURE: 'USERS_DELETE_FAILURE',
	
	// UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
	// UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
	
	// UPDATEPHOTO_SUCCESS: 'USER_UPDATEPHOTO_SUCCESS',
	// UPDATEPHOTO_REQUEST: 'USER_UPDATEPHOTO_REQUEST',
	
	//********MOVIES*************
	GENRE_REQUEST: 'USERS_GENRE_REQUEST',
	GENRE_SUCCESS: 'USERS_GENRE_SUCCESS',
	INIT_MOVIES_REQUEST: 'USERS_INIT_MOVIES_REQUEST',
	INIT_MOVIES_SUCCESS: 'USERS_INIT_MOVIES_SUCCESS',
	MOVIES_REQUEST: 'USERS_MOVIES_REQUEST',
	MOVIES_SUCCESS: 'USERS_MOVIES_SUCCESS',
	MOVIE_INFO_SUCCESS: 'USERS_MOVIE_INFO_SUCCESS',
	MOVIE_INFO_REQUEST: 'USERS_MOVIE_INFO_REQUEST',
	MOVIES_MORE_REQUEST: 'USERS_MOVIES_MORE_REQUEST',
	MOVIES_MORE_SUCCESS: 'USERS_MOVIES_MORE_SUCCESS',
	MOVIES_FILTER_SUCCESS: 'USERS_MOVIES_FILTER_SUCCESS',
	
	//SOCKET
	// INIT_ROOMS_SUCCESS: 'USER_INIT_ROOMS_SUCCESS',
	
	// ADD_MESSAGE_SUCCESS: 'USER_ADD_MESSAGE_SUCCESS',
	
	// INIT_NOTIF_SUCCESS: 'USER_INIT_NOTIF_SUCCESS',
	// ADD_NOTIF_SUCCESS: 'USER_ADD_NOTIF_SUCCESS',
	// READ_NOTIF_SUCCESS: 'USER_READ_NOTIF_SUCCESS',
	// UPDATE_USERSCONNECTED_SUCCESS: 'USER_UPDATE_USERSCONNECTED_SUCCESS'
};