export const userConstants = {

	LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
	LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',

	SIGNUP_PHOTO: 'USERS_SIGNUP_PHOTO',
	SIGNUP_REQUEST: 'USERS_SIGNUP_REQUEST',
	SIGNUP_SUCCESS: 'USERS_SIGNUP_SUCCESS',

	EMAIL_VERIFICATION_REQUEST: 'USERS_EMAIL_VERIFICATION_REQUEST',
	EMAIL_VERIFICATION_SUCCESS: 'USERS_EMAIL_VERIFICATION_SUCCESS',

	RESETPASS_EMAIL_REQUEST: 'USERS_RESETPASS_EMAIL_REQUEST',
	RESETPASS_EMAIL_SUCCESS: 'USERS_RESETPASS_EMAIL_SUCCESS',
	RESETPASS_TOKEN_REQUEST: 'USERS_RESETPASS_TOKEN_REQUEST',
	RESETPASS_TOKEN_SUCCESS: 'USERS_RESETPASS_TOKEN_SUCCESS',

	GET_COMMENT_REQUEST: 'USERS_GET_COMMENT_REQUEST',
	GET_COMMENT_SUCCESS: 'USERS_GET_COMMENT_SUCCESS',
	POST_COMMENT_REQUEST: 'USERS_POST_COMMENT_REQUEST',
	POST_COMMENT_SUCCESS: 'USERS_POST_COMMENT_SUCCESS',

	LOGOUT: 'USERS_LOGOUT',

	GETUSER_REQUEST: 'USERS_GETUSER_REQUEST',
	GETUSER_SUCCESS: 'USERS_GETUSER_SUCCESS',

	// GETPROFILE_REQUEST: 'USERS_GETPROFILE_REQUEST',
	// GETPROFILE_SUCCESS: 'USERS_GETPROFILE_SUCCESS',
	
	// DELETE_REQUEST: 'USERS_DELETE_REQUEST',
	// DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
	// DELETE_FAILURE: 'USERS_DELETE_FAILURE',
	
	// UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
	// UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
	
	// UPDATEPHOTO_SUCCESS: 'USER_UPDATEPHOTO_SUCCESS',
	// UPDATEPHOTO_REQUEST: 'USER_UPDATEPHOTO_REQUEST',
	
	//********MOVIES*************
	GENRE_REQUEST: 'USERS_GENRE_REQUEST',
	GENRE_SUCCESS: 'USERS_GENRE_SUCCESS',
	INIT_MOVIES_REQUEST: 'USERS_INIT_MOVIES_REQUEST',
	INIT_MOVIES_SUCCESS: 'USERS_INIT_MOVIES_SUCCESS',
	MOVIES_REQUEST: 'USERS_MOVIES_REQUEST',
	MOVIES_SUCCESS: 'USERS_MOVIES_SUCCESS',
	MOVIE_INFO_REQUEST: 'USERS_MOVIES_INFO_REQUEST',
	MOVIE_INFO_SUCCESS: 'USERS_MOVIES_INFO_SUCCESS',
	MOVIES_MORE_REQUEST: 'USERS_MOVIES_MORE_REQUEST',
	MOVIES_MORE_SUCCESS: 'USERS_MOVIES_MORE_SUCCESS',
	MOVIES_FILTER_SUCCESS: 'USERS_MOVIES_FILTER_SUCCESS',
	
	//SOCKET
	// INIT_ROOMS_SUCCESS: 'USER_INIT_ROOMS_SUCCESS',
	
	// ADD_MESSAGE_SUCCESS: 'USER_ADD_MESSAGE_SUCCESS',
	
	// INIT_NOTIF_SUCCESS: 'USER_INIT_NOTIF_SUCCESS',
	// ADD_NOTIF_SUCCESS: 'USER_ADD_NOTIF_SUCCESS',
	// READ_NOTIF_SUCCESS: 'USER_READ_NOTIF_SUCCESS',
	// UPDATE_USERSCONNECTED_SUCCESS: 'USER_UPDATE_USERSCONNECTED_SUCCESS'
};